Repository BuildForSDG/Team-203-TranSafe, pull requests merged in 2020-05, with the labels that each got.

#36 Meta edit app.properties file
  app.properties
Labels: documentation

#34 Update README.md
  README.md
Labels: bug

#50 Speed limit
  TranSafe/src/app/home/speedometer/speedometer.component.html
  TranSafe/src/app/home/speedometer/speedometer.component.scss
Labels: enhancement
